### ISSUE TITLE
Slow TTFB when using WP Offload Media and S3

### ISSUE THREAD

**Issue by joshuafredrickson** [clarifynl/responsive-pics#62]
I just launched a site that responded quickly until we set up WP Offload Media to offload to an S3 bucket. Everything works fine, but the TTFB jumps from 0.5s to 12.0s.

After some hunting, I found that the slowdown happens [here](https://github.com/clarifynl/responsive-pics/blob/88943cb13412f48768aedb3525e5e54a813af928/src/class-sources.php#L147-L164) in `get_resized_url`.

Basically, each source URL for each image runs a `file_exists` to an `s3east://` endpoint, causing the delay. In this site's case, it was running through 30 images on a page with ~7 sources per image. 

One option is to add attachment meta containing existing S3 sources and query that for S3 images instead of `file_exists`. Alternatively, we could use the S3 PHP SDK to check `doesFileExist`, but that seems expensive to run on every source file for every image on every non-cached page load, and I'm not sure if that would reduce the lag time.

I'm willing to lay some groundwork on this, but would love your input if you have any thoughts on how to handle it.

**Comment by Twansparant** [comment]
Hi @joshuafredrickson, thanks for reporting this!
Are you using the API in your site or just php/blade templates? It seems checking if a S3 asset exists is a network request instead of file system check, which make sit slow apparently (I have never noticed this t.b.h.). Are you sure the images were fully resized and not still in the action scheduler queue?
They only way to make sure if the resized image already exists in the S3 bucket is to keep track of it in the WP media attachment metadata indeed.

**Comment by joshuafredrickson** [comment]
I'm using `get_image_data` and `get_picture` and not the API. 

This particular site is high-traffic with 10k+ posts. This past week, the action scheduler queue has been constantly churning. I haven't had time to compare the queue to the files in the bucket yet, but at least on first glance, resized images are being offloaded.

I think maybe a combination of caching/expiring `file_exists` results on S3 plus an action hook for `file_exists` would be the best of both worlds. This would allow some default caching out of the box while allowing for additional or custom use cases. 

I'll try to make some initial progress for review.

**Comment by Twansparant** [comment]
Hi @joshuafredrickson, could you give version `1.8.0` a go and see if that fixes your issue?

**Comment by joshuafredrickson** [comment]
Awesome!

It looks like it's working as expected. Because it's using Offload Media's item cache, the newly generated sizes are listed in the `extra_info` column of `wp_as3cf_items`. This allows us to check that value for existing images vs reaching out to s3 for each individual check. 

Offload Media will also know to delete the generated images when an item is deleted from the Media Library.

Open to input on how to handle it better, but for now, this cut our TTFB by about two-thirds. 🥳 Thanks!

---
For reference: [Additional context on `s3` file paths.](https://github.com/clarifynl/responsive-pics/pull/63#issuecomment-1868103567)

**Comment by Twansparant** [comment]
Great!
Good to hear it improves performance so much!
So to be clear; this only happens when you have the `Remove local media` option checked.
The only scenario that still might occur is when an item is deleted directly in your S3 bucket, `ac3sf` would not know about this, unless it periodically checks your s3 bucket, but my guess is it doesn't.

**Comment by joshuafredrickson** [comment]
Yeah, I'm not 100% on how AS3CF handles manually deleted bucket objects. But I think that by the time you're using AS3CF to handle offloading and removing files, you probably shouldn't be manually deleting items from the bucket. 

At the very least, it's "Manually delete at your own risk." 😄
